### PR TITLE
Fix files mentioned in MANIFEST

### PR DESCRIPTION
**Pull request by akrherz**
I am by no means a packaging expert, but I suspect this needs to be replaced with a MANIFEST.in file at some point?  Regardless, this should fix things up for builds

### CODE REVIEW

**Comment by phobson** [comment]
You're probably right, but I think modifications to setup.py I've made take care of this. Would be interesting to remove `MANIFEST` entirely to see how Travis likes that.

**Comment by phobson** [comment]
Note: travis failure seems unrelated to this PR. I'll pull from your branch and test on my machines when I get the chance.

**Comment by akrherz** [comment]
Thanks for the response.  What prompted this PR was running `python setup.py bdist_rpm` on python27 resulted in an RPM with only the `__init__.py` file included.

**Comment by phobson** [comment]
Ahh very good to know. I've never built an RPM. If you don't mind, I'll take a bit of time to test on my systems and try to fix travis (it's probably an old conda version) before merging. 99% sure this is ready to go though.

**Comment by phobson** [comment]
Got travis happy again. Could you rebase this from master?

**Comment by akrherz** [comment]
@phobson I think I have rebased now

**Comment by phobson** [comment]
Cool. Thanks for the PR! 

Can I bug in the future about your opinions about the API and what not? I feel like the way `Station` holds data is pretty clunky.

**Comment by akrherz** [comment]
I always like to give my two cents, but I am not the sharpest tool in the toolbox though!

**Pull request merged**
