### PR TITLE
fixed typo in metar/station.py - changed sat_id into sta_id & stuff

### PR DESCRIPTION
**Pull request by marjetika**

### CODE REVIEW

**Comment by marjetika** [comment]
@coveralls What do you mean? I changed "**sat**_id" to "**sta**_id"

**Comment by phobson** [comment]
Thanks for this @marjetika. Could you rebase to get rid of the merge commit?

**Comment by phobson** [comment]
@mat Or better yet, make the pull request from your feature branch, not from your master branch.

**Comment by phobson** [comment]
@marjetika coveralls is an automated service. you changes don't affect the test coverage, so you don't need to worry about it.

**Comment by marjetika** [comment]
How do I rebase? I'm just starting with github (I have experience with git in command-line)

**Comment by phobson** [comment]
@marjetika see my second suggestion. make (maybe a new PR) from your feature branch.  

matplotlib has good docs on the preferred development workflow.

**Comment by marjetika** [comment]
Option 1:
github.com doesn't seem to have otion to rebase. I looked around and I can't find anything.

Option 2:
I deleted feature branch, so I can't get to it.

**Comment by marjetika** [comment]
@phobson - you recommended

> matplotlib has good docs on the preferred development workflow. http://matplotlib.org/devel/gitwash/development_workflow.html

This doesn't include information of the github website and forks.

**Comment by phobson** [comment]
closed via #68

**Pull request closed without merging**
