### PR TITLE
Changed self.text_list to text_list in metar.py …

### PR DESCRIPTION
**Pull request by nguy**
Changed from global to local variable at L1405 to fix.

### CODE REVIEW

**Comment by phobson** [comment]
Awesome, @nguy. Thanks!

**Comment by nguy** [comment]
You bet.  I'm hoping to use this package more in the next couple of months, so hopefully I'll be digging into the code a bit more.

**Comment by phobson** [comment]
Good deal. Be sure to pipe up if you have any questions. The Regex stuff all came from the original author. I just added to visualization and bulk downloads via the WeatherStation class. Known bugs in my wind direction resampling algorithms. I have a fix, but need to test and do that whole song and dance. 



—

**Comment by nguy** [comment]
Used the Metar class to process and post to a web page! Just push the
'Display_Metar_Text' button.

http://www.atmos.uwyo.edu/~bguy/weather.shtml

**Comment by phobson** [comment]
@nguy  this is so cool! thanks for sharing!

**Pull request merged**
