### PR TITLE
moving test and data files to use/test without install

### PR DESCRIPTION
**Pull request by tdihp**
Hi. I've moved some files.

The main problem I met was that `metar.station.getAllStations` access the file from sys.prefix,
which point to a wrong path on my machine.

The standard way to deal with "package data" is through `pkg_resources`,
because installed python package could be a single egg file, without path.

Which lead me to move tests outside of the package, to avoid this awkwardness
of accessing test data.

And, BTW, if you have an installed version of `metar`, nosetests would do "magic" to import local version of `metar` instead of installed.

Hope you find this helpful.

### CODE REVIEW

**Comment by phobson** [comment]
Thanks for the PR. I'm all for better packaging as I'm terrible at it. Could you also modify the Travis config file to get the CI back up and running?

**Comment by tdihp** [comment]
OK now travis passed.

Also there's another thing:
I'm not sure what does `NoseWrapper` in metar/__init__.py do,
so I haven't moved it. If it's to be moved to tests,
setup.py may also need to change a bit.

**Comment by phobson** [comment]
The `NoseWrapper` let's you do:

```python
import metar
metar.test()

```

Note sure if it ever worked though.

**Comment by tdihp** [comment]
Ahh, I see...

Since I've moved tests out of the package, The tests won't be reachable by `metar` package anyway.

**Comment by phobson** [comment]
hmmm -- well I'd like to still be able to use `metar.test()`. Is there a way to solve the `getAllStations` problem w/o losing that?

**Comment by tdihp** [comment]
You'll end up doing all test data access similar way as getAllStations in this PR.

BTW if you are to have a test function in package, it's better if it's in an isolated module, instead in the __init__.py of the `metar` module (e.g. metar/testing.py , similar to numpy.testing), to avoid polluting the namespace.

**Comment by phobson** [comment]
numpy as a `test` function and a `testing` module. The function runs all of the unit tests. The module contains numpy-specific utilities to facilitate unit testing with numpy objects. 

I like my packages to maintain a similar structure.

**Comment by tdihp** [comment]
> I like my packages to maintain a similar structure.

Yes I understand.

And I am suggesting that the current test behavior is *wrong* ---- it will write files to `os.path.join(sys.prefix, 'metar_data', 'test_data', filename)`, which is a folder may or may not exist, and the user may or may not have write access to, and is certainly not the place where normal test output files go. It seems a bigger problem to me, than having a `metar.test()`, so I made a simple fix, by moving the tests out of the package.

If you want the in-package test back, you can always move the tests into the package, **after** changing where test outputs go to. Moving tests is rather trivial, so is changing test output directory. But I think it's better to keep the PR this way, and change those later.

**Comment by phobson** [comment]
> And I am suggesting that the current test behavior is wrong 

That's pretty clear now. Thanks for the explanation.

So it seems like the destination of the test output is an orthogonal issue to the location of the tests. Is that right? Does this PR handle the former or just the latter?

**Comment by tdihp** [comment]
> So it seems like the destination of the test output is an orthogonal issue to the location of the tests. Is that right? Does this PR handle the former or just the latter?

I think the issue here is "Separate test data and output".

By moving the tests out of the package, this PR simply write output to `tests/data` folder relative to the repository root (I just changed `getTestFile`). Which I think is only OK if the tests are not to be installed. I chose to fix this way because I can fix the test file input/output without changing actual test code.

However in-package test have to separate test data (bundled in the package) and test output (somewhere like `/tmp/{randomhash}` or `{PWD}/metar_test_output`), which require further effort changing tests that does use test data or produce output.

**Comment by phobson** [comment]
Thanks @tdihp

**Pull request merged**
