### PR TITLE
fixed bug that misparsed visibility as a wind group

### PR DESCRIPTION
**Pull request by marjetika**
Discovered by XavierCLL and implemented in the [TomP's version of python-metar](https://github.com/tomp/python-metar) repository.
See [tomp@bea7e7b?diff=split](tomp@bea7e7b?diff=split)

### CODE REVIEW

**Comment by marjetika** [comment]
I noticed that there were some recent changes in Tom Pollard's version of python-metar. I would like to implement useful changes to @phobson 's version.
I am not sure about this change - I haven't personally verified it yet.

**Comment by marjetika** [comment]
By the way, @phobson, could you add **_issues_** to this repository?

**Comment by phobson** [comment]
@marjetika now that the source (Tom's) version is python-3 compatible, i'm probably going to delete this fork.

**Comment by marjetika** [comment]
No, don't! There are several differences between the forks. When I was researching which one to use for my project, yours was significantly superior.

**Comment by phobson** [comment]
@marjetika my plan is to subclass Tom `metal.metar` class in my cloud side library and keep all of the enhancements there: https://github.com/phobson/cloudside.

I'll merge this in the meantime.

**Comment by phobson** [comment]
@marjetika 
I've subclassed Tom P's metar class in `cloudside` master as of this commit:
https://github.com/Geosyntec/cloudside/tree/baa8b784aa8263f1b627b564e31cefc5ae447562

AFAICT that has let's me do all the things I was doing with this fork of `metar`. 

Kick the tires on that and let me know what you think. I'd like sync this fork back up with Tom P's repo soon.

**Comment by akrherz** [comment]
@phobson I'm struggling trying to figure out where the latest and greatest `metar` is :)  Is the hope to send the `master-backup` branch upstream to tomp or the `master` branch or ?

**Comment by phobson** [comment]
Hey @akrherz. It really depends on what you're trying to do. Like I said in the message above this. I've unforked from https://github.com/tomp/python-metar and use his code as the canonical version.

If you want a functionally equivalent version of what my fork used to do, you need to install Tom's python-metar package and https://github.com/Geosyntec/cloudside. 

In `cloudside`, I subclass and modify the upstream parser to do what I needed it to do for bulk data downloads and parsing. The subclass is `cloudside.station.MetarParser`.

**Comment by akrherz** [comment]
Hi @phobson , thank you kindly for the response.  I am still confused though as your `master-backup` branch is significantly different (200 some commits and contains patches like mine for snowdepth) than upstream tomp/master and even your cloudside one.  Your recent `master` changes though seen to have changes not in `master-backup`, which is confusing me even more :(

I guess my goal is to figure out where to send pull requests to and straighten out where upstream is :)

btw, I have a fairly robust source of METARs via a CGI-hacky API. see an R implementation here https://github.com/ropensci/riem

**Comment by phobson** [comment]
Like I said, I had forked from Tom P -- the original author. He is and forever will be upstream. I'm just holding unto `master-backup` in case I find any bugs in `cloudside` (I haven't...yet).

**Comment by akrherz** [comment]
@phobson thanks again for indulging me here.  So I will attempt to get some of your `master-backup` commits I need upstream to tomp/master, so that I can base my work on his repo.

**Comment by akrherz** [comment]
Hi @phobson , I think I am following you now, but there are things you fixed / implemented outside of `Metar.__init__` that I need, like my `snowdepth` patch, which does not exist in your cloudside subclass, for example.

**Comment by phobson** [comment]
OK -- I understand. Those types of things are better pushed upstream to Tom
(and I now see that *you* authored them).

Holler at me over at cloudside if you get a lot friction or need things to
move faster.
-paul

**Comment by akrherz** [comment]
hi @phobson , so it has been a while and I am unsure how to 'holler at you over at cloudside', so will bump this old issue!  So tomp has agreed to move his `python-metar` into an org repo on github and I am attempting to take up the reigns on this while also figuring out how to possibly implement a metar parser in `MetPy`.  So am unsure what the future holds, but will try to push `python-metar` ahead a bit.

Would you mind if I attempted to cherry-pick some of your changes 'back upstream' ?

**Comment by phobson** [comment]
hey @akrherz, sure. would you mind creating and tagging me in a couple of issues over at the new repo so I can see what you mean. maybe i can help out a bit.

**Pull request merged**
